# Generated by Django 4.1.7 on 2023-04-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Picturegram',
        ),
    ]
