# Generated by Django 4.1.7 on 2023-04-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturegram',
            old_name='likes',
            new_name='like_count',
        ),
    ]
